module.exports = {
  expo: {
    name: "Flo Orders",
    slug: "flo-orders",
    version: "1.0.0",
    scheme: "floorders",
    platforms: ["ios", "android"],
    newArchEnabled: false,
    orientation: "default",
    icon: "./assets/images/favicon.png",
    userInterfaceStyle: "automatic",
    splash: {
      image: "./assets/images/flo-logo.png",
      resizeMode: "contain",
      backgroundColor: "#ffffff"
    },
    assetBundlePatterns: [
      "**/*"
    ],
    android: {
      package: "com.floorders.floorders",
      versionCode: 6,
      icon: "./assets/images/favicon.png",
      adaptiveIcon: {
        foregroundImage: "./assets/images/favicon.png",
        backgroundColor: "#ffffff"
      },
      googleServicesFile: "./app/google-services.json",
      // Privacy Policy URL - REQUIRED for Google Play Store submission
      privacy: "https://kawerifytech.com/privacy-policy",
      statusBar: {
        barStyle: "default",
        backgroundColor: "#ffffff"
      }
    },
    ios: {
      supportsTablet: true,
      bundleIdentifier: "com.floorders",
      buildNumber: "6",
      googleServicesFile: "./app/GoogleService-Info.plist",
      deploymentTarget: "15.1",
      requireFullScreen: false,
      config: {
        usesNonExemptEncryption: false
      },
      privacyManifests: {
        NSPrivacyAccessedAPITypes: [
          {
            NSPrivacyAccessedAPIType: "NSPrivacyAccessedAPICategoryUserDefaults",
            NSPrivacyAccessedAPITypeReasons: ["CA92.1"]
          },
          {
            NSPrivacyAccessedAPIType: "NSPrivacyAccessedAPICategoryFileTimestamp",
            NSPrivacyAccessedAPITypeReasons: ["C617.1"]
          }
        ]
      },
      // Privacy Policy URL - REQUIRED for App Store submission
      privacy: "https://kawerifytech.com/privacy-policy",
      infoPlist: {
        NSAppTransportSecurity: {
          NSAllowsArbitraryLoads: false,
          NSExceptionDomains: {
            "firebaseapp.com": {
              NSExceptionAllowsInsecureHTTPLoads: false,
              NSExceptionMinimumTLSVersion: "1.2"
            },
            "googleapis.com": {
              NSExceptionAllowsInsecureHTTPLoads: false,
              NSExceptionMinimumTLSVersion: "1.2"
            }
          }
        },
        // Permission usage descriptions - REQUIRED for App Store if permissions are requested
        NSUserNotificationsUsageDescription: "We need notification permissions to send you important updates about your fuel orders and transactions.",
        CFBundleURLTypes: [
          {
            CFBundleURLName: "com.floorders",
            CFBundleURLSchemes: ["com.floorders"]
          }
        ],
        UISupportedInterfaceOrientations: [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationPortraitUpsideDown"
        ],
        "UISupportedInterfaceOrientations~ipad": [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationPortraitUpsideDown",
          "UIInterfaceOrientationLandscapeLeft",
          "UIInterfaceOrientationLandscapeRight"
        ],
        UIRequiredDeviceCapabilities: ["armv7"],
        UIStatusBarStyle: "UIStatusBarStyleDefault",
        UIViewControllerBasedStatusBarAppearance: true
      }
    },
    plugins: [
      [
        "expo-build-properties",
        {
          ios: {
            deploymentTarget: "15.1",
            flipper: false
          },
          android: {
            compileSdkVersion: 35,
            targetSdkVersion: 35,
            minSdkVersion: 24
          }
        }
      ],
      "expo-font",
      "expo-router",
      "expo-web-browser",
      "expo-splash-screen",
      "expo-notifications"
    ],
    extra: {
      eas: {
        projectId: "de9759a5-a92e-48f8-aca2-ac2959cfd7c8"
      }
    },
    // This project uses prebuild (CNG - Continuous Native Generation)
    // Native folders (android/, ios/) are generated by prebuild from app.config.js
    // Custom files like google-services.json are preserved via app.config.js references
    // Use "npm run doctor" instead of "npx expo-doctor" to avoid warnings
  }
};
